### ISSUE TITLE
Support for job queue latency for Que 0.x?

### ISSUE THREAD

**Issue by prognostikos** [hirefire/hirefire-resource-ruby#67]
Probably an extremely niche thing, but would you accept a PR to enable job queue latency for Que 0.x?

**Comment by mrrooijen** [comment]
[hirefire-resource v1.0.3](https://rubygems.org/gems/hirefire-resource/versions/1.0.3) was released which includes backwards compatibility with `que ~> 0` and `que ~> 1`. Both `#job_queue_size` and `#job_queue_latency` are supported.

**Comment by prognostikos** [comment]
@mrrooijen thanks for this and sorry that I haven't been able to test this yet, I'll give it a go with the new version.

**Comment by mrrooijen** [comment]
All good! Let me know if you run into problems. 👍
