### ISSUE TITLE
Hirefire Dyno Manager name limit

### ISSUE THREAD

**Issue by plribeiro3000** [hirefire/hirefire-resource-ruby#69]
I'm trying to create a new infrastructure based on `sidekiq` and `hirefire` and since the number might scale a lot we need the name to  be a little bit bigger than the current regular expression supports.

I just checked `Hirefire` and it does support names longer than 29 characters so why is there a lock for it?

Could i open a PR to remove this constraint?

**Comment by mrrooijen** [comment]
Hi @plribeiro3000 I've just released v1.0.5 which increases the limit to 63 characters. Any more than that and Heroku will reject deployments.

**Comment by plribeiro3000** [comment]
@mrrooijen Awesome Michael!

Than you for the fast work on this!

**Comment by mrrooijen** [comment]
Glad to help!
